Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheCoffeeShop.Models;

namespace TheCoffeeShop.Controllers
{
    public class BlogController : Controller
    {
        private readonly CoffeeShopDbContext _context;

        public BlogController(CoffeeShopDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> UserIndex(string searchString, string category)
        {
            // Lấy danh sách bài viết kèm thông tin tác giả và sản phẩm liên quan
            var blogs = _context.Blogs
                .Include(b => b.Account)
                .Include(b => b.Product)
                .OrderByDescending(b => b.BlogDate)
                .AsQueryable();

            // Xử lý tìm kiếm nếu có
            if (!string.IsNullOrEmpty(searchString))
            {
                blogs = blogs.Where(b =>
                    b.BlogName.Contains(searchString) ||
                    b.BlogContent.Contains(searchString));
            }

            // Xử lý lọc theo danh mục nếu có
            // Lưu ý: Trong thực tế, bạn cần thêm trường Category vào model Blog
            // Đây chỉ là ví dụ, bạn có thể điều chỉnh theo cấu trúc dữ liệu thực tế
            if (!string.IsNullOrEmpty(category) && category != "all")
            {
                // Giả sử có trường Category trong Blog
                // blogs = blogs.Where(b => b.Category == category);
            }

            return View("UserIndex", await blogs.ToListAsync());
        }


        // GET: Blog
        public async Task<IActionResult> Index()
        {
            var coffeeShopDbContext = _context.Blogs.Include(b => b.Account).Include(b => b.Product);
            return View(await coffeeShopDbContext.ToListAsync());
        }

        // GET: Blog/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Account)
                .Include(b => b.Product)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // GET: Blog/Create
        [Authorize(Roles = "2, 3")]
        public IActionResult Create()
        {
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId");
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId");
            return View();
        }

        // POST: Blog/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Create([Bind("BlogId,BlogName,BlogDate,BlogContent,BlogImage,AccountId,ProductId")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blog);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId", blog.AccountId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", blog.ProductId);
            return View(blog);
        }

        // GET: Blog/Edit/5
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId", blog.AccountId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", blog.ProductId);
            return View(blog);
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Edit(int id, [Bind("BlogId,BlogName,BlogDate,BlogContent,BlogImage,AccountId,ProductId")] Blog blog)
        {
            if (id != blog.BlogId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.BlogId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "AccountId", "AccountId", blog.AccountId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", blog.ProductId);
            return View(blog);
        }

        // GET: Blog/Delete/5
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.Blogs
                .Include(b => b.Account)
                .Include(b => b.Product)
                .FirstOrDefaultAsync(m => m.BlogId == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.Blogs.FindAsync(id);
            if (blog != null)
            {
                _context.Blogs.Remove(blog);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.Blogs.Any(e => e.BlogId == id);
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TheCoffeeShop.Models;

public class OrderController : Controller
{
    private readonly CoffeeShopDbContext _context;

    public OrderController(CoffeeShopDbContext context)
    {
        _context = context;
    }
    [Authorize(Roles = "3")]
    public async Task<IActionResult> AdminIndex()
    {
        // Lấy danh sách đơn hàng kèm theo thông tin liên quan
        var orders = await _context.Orders
            .Include(o => o.Account)
            .Include(o => o.Cart)
                .ThenInclude(c => c.Product)
            .ToListAsync();

        // Thống kê cho dashboard
        ViewBag.TotalOrders = orders.Count;
       

        return View(orders);
    }

   


    // GET: /Order
    public async Task<IActionResult> Index()
    {
        var accountId = HttpContext.Session.GetInt32("AccountId");
        if (accountId == null)
        {
            return RedirectToAction("Index", "Account");
        }

        var carts = await _context.Carts
            .Where(c => c.AccountId == accountId)
            .Include(c => c.Product)
            .ToListAsync();

        return View(carts);
    }

    // POST: /Order/Confirm
    [HttpPost]
    public async Task<IActionResult> Confirm()
    {
        var accountId = HttpContext.Session.GetInt32("AccountId");

        if (accountId == null)
        {
            return RedirectToAction("Index", "Account");
        }

        var carts = await _context.Carts
            .Where(c => c.AccountId == accountId)
            .Include(c => c.Product)
            .ToListAsync();

        if (!carts.Any())
        {
            return RedirectToAction("Index", "ShoppingCart");
        }

        foreach (var cartItem in carts)
        {
            var CartID = cartItem.CartId;
            if (CartID == null)
            {
                Console.WriteLine("CartID is null",CartID);
            }
            var order = new Order
            {
                AccountId = accountId,
                CartId = cartItem.CartId,
                OrderDate = DateTime.Now
            };

            _context.Orders.Add(order);
        }
        
        await _context.SaveChangesAsync();

        TempData["Message"] = "Đặt hàng thành công!";
        return RedirectToAction("ThankYou");
    }

    public IActionResult ThankYou()
    {
        return View();
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheCoffeeShop.Models;

namespace TheCoffeeShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly CoffeeShopDbContext _context;

        public ProductController(CoffeeShopDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "3")]
        public async Task<IActionResult> AdminIndex()
        {
            // Lấy danh sách sản phẩm kèm theo thông tin danh mục
            var products = await _context.Products
                    .Include(p => p.Category)
                    .ToListAsync();

            // Lấy danh sách danh mục cho dropdown filter
            var categories = await _context.Categories.ToListAsync();

            // Thiết lập các thông tin thống kê cho dashboard
            ViewBag.TotalProducts = products.Count;
            ViewBag.TotalCategories = categories.Count;
            ViewBag.BestSellingProducts = await _context.Products.CountAsync(p => p.ProductPrice > 0); // Placeholder, thay bằng logic thực tế
            ViewBag.OutOfStockProducts = 0; // Placeholder, thay bằng logic thực tế

            // Thiết lập danh sách danh mục cho dropdown filter
            ViewBag.Categories = categories;

            return View(products);
        }
        //GET: Product
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Index()
        {
            var coffeeShopDbContext = _context.Products.Include(p => p.Category);
            var accountId = HttpContext.Session.GetInt32("AccountId");
            if (accountId == null)
            {
                return RedirectToAction("Index", "Account");
            }

            // Lấy danh sách sản phẩm trong giỏ hàng
            var carts = _context.Carts.Where(c => c.AccountId == accountId).Include(c => c.Product).ToList();

            // Tính tổng số lượng sản phẩm trong giỏ hàng
            int cartTotalQuantity = (int)carts.Sum(item => item.Quality);

            // Đặt giá trị vào ViewBag để hiển thị trên nút giỏ hàng
            ViewBag.CartCounts = cartTotalQuantity;
            return View(await coffeeShopDbContext.ToListAsync());
        }
        [Authorize(Roles = "1, 2, 3")]
        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        [Authorize(Roles = "2, 3")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId");
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ProductPrice,Description,Size,ProductImage,CategoryId")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // GET: Product/Edit/5
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ProductPrice,Description,Size,ProductImage,CategoryId")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryId", product.CategoryId);
            return View(product);
        }

        // GET: Product/Delete/5
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "2, 3")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
        // GET: Product/Menu
        public async Task<IActionResult> Menu()
        {
            var products = await _context.Products
                .Include(p => p.Category)
                .ToListAsync();
            return View(products);
        }

       


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Coffee Shop</title>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    @* <link href="~/css/site.css" rel="stylesheet" type="text/css" /> *@
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <div class="container">
            <nav class="main-nav">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home")">Coffee Shop</a>
                </div>
                <ul class="nav-links">
                    <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li><a href="@Url.Action("Menu", "Product")">Menu</a></li>
                    <li><a href="@Url.Action("UserIndex", "Blog")">Blog</a></li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("3"))
                    {
                        <li><a href="@Url.Action("AdminIndex", "Order")">Manage</a></li>
                        
                    }
                   
                </ul>
                <div class="cart">
                    <div class="cart">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a href="@Url.Action("Index", "Account")" class="btn btn-primary login-btn">
                                Đăng nhập
                            </a>
                        }
                        else
                        {
                            <form action="@Url.Action("Logout", "Account")" method="post" id="logoutForm" style="display: inline;">
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-outline-primary logout-btn">
                                    Đăng xuất
                                </button>
                            </form>
                        }
                    </div>

                @* @if (User.Identity.IsAuthenticated) *@
                @* { *@
                @*     <div class="cart"> *@
                @*         <form asp-action="Logout" asp-controller="Account" method="post" id="logoutForm" class="logout-form"> *@
                @*             <button type="submit" class="btn btn-primary logout-btn"> *@
                @*                 Log Out *@
                @*             </button> *@
                @*         </form> *@
                @*     </div> *@
                @* } *@
            </nav>
        </div>
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
        <div class="container">
            <div class="footer-content">
                <div class="footer-logo">
                    <h3>Coffee Shop</h3>
                    <p>Your perfect coffee experience</p>
                </div>
                <div class="footer-links">
                    <h4>Quick Links</h4>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Menu</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="footer-contact">
                    <h4>Contact Us</h4>
                    <p><i class="fas fa-map-marker-alt"></i> 123 Coffee Street, City</p>
                    <p><i class="fas fa-phone"></i> +1 234 567 890</p>
                    <p><i class="fas fa-envelope"></i> info@coffeeshop.com</p>
                </div>
                <div class="footer-social">
                    <h4>Follow Us</h4>
                    <div class="social-icons">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; @DateTime.Now.Year Coffee Shop. All Rights Reserved.</p>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js">  </script>
    <script src="~/Scripts/site.js"></script>
   
    @RenderSection("scripts", required: false)
    
    <style>

        header {
            background-color: rgba(255, 255, 255, 0.95);
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            position: fixed;
            width: 100%;
            top: 0;
            left: 0;
            z-index: 1000;
        }

        .main-nav {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px 0;
        }

        .logo a {
            font-family: "Playfair Display", serif;
            font-size: 1.8rem;
            color: #3a2a18;
            text-decoration: none;
            font-weight: 700;
        }

        .nav-links {
            display: flex;
            list-style: none;
            margin: 0;
            padding: 0;
        }

            .nav-links li {
                margin: 0 15px;
            }

            .nav-links a {
                color: #333;
                text-decoration: none;
                font-weight: 500;
                transition: color 0.3s ease;
            }

                .nav-links a:hover {
                    color: #c8a97e;
                }

        /* Footer */
        footer {
            background-color: #1a1a1a;
            color: #fff;
            padding: 60px 0 20px;
        }

        .footer-content {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 30px;
            margin-bottom: 40px;
        }

        .footer-logo h3 {
            font-family: "Playfair Display", serif;
            font-size: 1.8rem;
            margin: 0 0 10px;
        }

        .footer-logo p {
            color: #999;
        }

        .footer-links h4,
        .footer-contact h4,
        .footer-social h4 {
            margin-bottom: 20px;
            font-size: 1.2rem;
        }

        .footer-links ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .footer-links li {
            margin-bottom: 10px;
        }

        .footer-links a {
            color: #999;
            text-decoration: none;
            transition: color 0.3s ease;
        }

            .footer-links a:hover {
                color: #c8a97e;
            }

        .footer-contact p {
            margin-bottom: 10px;
            color: #999;
        }

        .footer-contact i {
            margin-right: 10px;
            color: #c8a97e;
        }

        .social-icons {
            display: flex;
        }

            .social-icons a {
                width: 40px;
                height: 40px;
                background-color: #333;
                border-radius: 50%;
                display: flex;
                align-items: center;
                justify-content: center;
                color: white;
                margin-right: 10px;
                transition: background-color 0.3s ease;
            }

                .social-icons a:hover {
                    background-color: #c8a97e;
                }

        .footer-bottom {
            border-top: 1px solid #333;
            padding-top: 20px;
            text-align: center;
            color: #999;
        }

        /* Adjust main content to account for fixed header */
        main {
            padding-top: 80px;
        }

        

        

      

        /* Mobile menu */
        .menu-toggle {
            display: none;
            cursor: pointer;
            font-size: 1.5rem;
            color: #333;
        }


        .login-btn {
            background-color: #dc3545;
            color: white;
            border-radius: 30px;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s;
            text-decoration: none;
        }

            .login-btn:hover {
                background-color: #0056b3;
            }

        /* Nút đăng xuất */
        .logout-btn {
            background-color: #dc3545;
            color: white;
            border-radius: 30px;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

            .logout-btn:hover {
                background-color: #c82333;
            }

        }
    </style>
</body>
</html>